version: '3.8'

services: 
  prometheus:
    image: prom/prometheus:v2.45.3
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 5000:5000
    expose:
      - 5000
  node_backend: 
    container_name: node_backend
    image: node-test:1.0.0
    build:
      context: .
      #dockerfile: .Dockerfile
    ports:
      - '3000:3000'
    environment:
    - PGUSER=postgres
    - PGPASSWORD=123456
    - PGDATABASE=takemeoutdb
    - PGHOST=db # NAME OF THE SERVICE
    depends_on: 
      - db
  db:
    container_name: db
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=takemeoutdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
  prometheus_data: {}
  grafana_data: {}