version: '3.8'

services: 
  node_backend: 
    container_name: node_backend
    image: node-test:1.0.0
    build:
      context: .
      #dockerfile: .Dockerfile
    ports:
      - '3000:3000'
    environment:
    - PGUSER=postgres
    - PGPASSWORD=Erwy1995
    - PGDATABASE=takemeoutdb
    - PGHOST=db # NAME OF THE SERVICE
    depends_on: 
      - db
  db:
    container_name: db
    image: 'postgres:14'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Erwy1995
      - POSTGRES_DB=takemeoutdb
    volumes:
      - pgdata1:/var/lib/postgresql/data

volumes:
  pgdata1: {}
