apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: staging
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: postgres-config
#   namespace: staging
#   labels:
#     app: database
# data:
#   POSTGRES_USER: postgres
#   POSTGRES_DB: takemeoutdb

---
apiVersion: v1
data:
  password: MTIzNDU2
kind: Secret
metadata:
  name: postgres-secret
  namespace: staging
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
        app: database
    spec:
      containers:
        - name: database
          image: postgres:14
          volumeMounts:
            # - name: database-persistent-storage
            #   mountPath: /var/lib/postgresql/data
            - name: test-volume
              mountPath: /var/lib/postgresql/data

            # - name: postgres-config
            #   mountPath: /etc/postgresql
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: takemeoutdb

          imagePullPolicy: Always 
      volumes:
        # - name: database-persistent-storage
        #   persistentVolumeClaim:
        #     claimName: ebs-claim
        - name: test-volume
          emptyDir:
            sizeLimit: 500Mi


        # - name: postgres-config 
        #   configMap:
        #     name: postgres-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: db-storage
  resources:
    requests:
      storage: 5Gi