#using efs as it allows multiple instances to write on it
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: db-storage
volumeBindingMode: WaitForFirstConsumer
provisioner: ebs.csi.aws.com
parameters:
  directoryPerms: "700"